DELETE FROM custom_materials
WHERE name IN (
  'Standard 15A Receptacle Assembly',
  'Standard 20A Receptacle Assembly',
  'GFCI 15A Receptacle Assembly',
  'GFCI 20A Receptacle Assembly',
  'AFCI 15A Receptacle Assembly',
  'USB Receptacle Assembly',
  'Weatherproof GFCI Assembly',
  'Floor Receptacle Assembly',
  'Single Pole Switch Assembly',
  '3-Way Switch Assembly',
  '4-Way Switch Assembly',
  'Dimmer Switch Assembly',
  'Motion Sensor Switch Assembly',
  'Timer Switch Assembly',
  'Smart Switch Assembly',
  '4 Inch Recessed Light Assembly',
  '6 Inch Recessed Light Assembly',
  'Flush Mount Ceiling Light Assembly',
  'Pendant Light Assembly',
  'Vanity Light 3-Light Assembly',
  'Chandelier Assembly',
  'Ceiling Fan with Light Assembly',
  'Outdoor Wall Light Assembly',
  '30W LED Flood Light Assembly',
  'Motion Sensor Flood Light Assembly',
  'Hardwired Smoke Detector Assembly',
  'Smoke CO Combo Detector Assembly',
  'CO Detector Assembly',
  'Doorbell System Assembly',
  'Programmable Thermostat Assembly',
  'Smart Wi-Fi Thermostat Assembly',
  'Dryer Outlet 4-Prong Assembly',
  'Range Outlet 4-Prong Assembly',
  'Welder Outlet 50A Assembly',
  '15A Dedicated Circuit Assembly',
  '20A Dedicated Circuit Assembly',
  '30A Dedicated Circuit Assembly',
  '40A Dedicated Circuit Assembly',
  '50A Dedicated Circuit Assembly',
  '20A GFCI Protected Circuit Assembly',
  '15A AFCI Protected Circuit Assembly',
  '20A AFCI Protected Circuit Assembly',
  '100A Sub Panel Assembly',
  '200A Sub Panel Assembly',
  '100A Service Panel Upgrade',
  '200A Service Panel Upgrade',
  'Whole House Surge Protector',
  'Ground Rod Assembly',
  'Main Bonding Jumper Assembly',
  'LED Exit Sign Assembly',
  'Emergency Light Assembly',
  'Under Cabinet LED Light Assembly',
  '8ft Track Lighting System',
  'Landscape Light Set 6-Pack',
  'Dusk to Dawn Light Assembly',
  'Bathroom Exhaust Fan Assembly',
  'Bath Fan Light Combo Assembly',
  'Bathroom Heater Assembly',
  'Bathroom GFCI Circuit Package',
  'Kitchen Counter Outlet Circuit',
  'Garage 20A Circuit Package',
  'Outdoor GFCI Outlet Assembly',
  'Outdoor Post Light Assembly',
  'Motion Security Light 2-Head',
  'Hot Tub 50A Circuit Assembly',
  'EV Charger 40A Circuit',
  'Workshop 20A Circuit Package',
  'Cat6 Data Outlet Assembly',
  'Coax Cable Outlet Assembly',
  'Combo Data Coax Outlet Assembly',
  'AC Disconnect 60A Assembly',
  'Generator Inlet 30A Assembly',
  'Manual Transfer Switch Assembly',
  'Photocell Lighting Control Assembly',
  '30A Lighting Contactor Assembly',
  'Outdoor Timer Control Assembly',
  'Commercial Occupancy Sensor'
);

-- Verify deletion
SELECT COUNT(*) as deleted_count FROM custom_materials 
WHERE name LIKE '%Assembly%' OR name LIKE '%Circuit%';
